### ISSUE TITLE
Symbols.star_rounded/grade_rounded alignment is off

### ISSUE THREAD

**Issue by auradigitaldev** [timmaffett/material_symbols_icons#29] opened 2024-07-11 07:11 UTC
Hey there, I noticed that the `star_rounded` (aka `grade_rounded`) symbols aren't well-aligned (this is with 24dp). Below I've attached a screenshot of the icon with overlay guidelines to show that the icon itself isn't centered.

IIUC this repo automatically pulls from Material Symbols so I guess this could potentially be an issue with the Material Symbols resources? But just wanted to check.

![photo](https://github.com/timmaffett/material_symbols_icons/assets/134808323/0d9ab76a-758b-4741-ac13-5993a8c9d837)

**Comment by timmaffett** [comment] 2024-07-12 19:07
Hi @auradigitaldev ,
   Yes each time the package is built the fonts are pulled from the official material design repo.  

I believe if you are seeing an issue that it the font/icon rendering is as intended by the authors of the official font.

The font's metrics are patched so they work correctly (are properly centered vertically) with older (non master branch) versions of flutter.  I verified that this patched did indeed occur for the current release (4.2768.0).  The metrics that are patched do not effect any change except in the older versions of the flutter engine.  The bug in flutter icon positioning has been fixed on the master branch (and may have also now been migrated to stable, not sure).   At some point I will no longer have to patch the fonts at all once the older affected versions of the flutter engine are no longer commonly used.   When this occurs I will be able to use the raw fonts without modification.   The patched versions allow the font to render correctly on all versions of the flutter engine.

If you are interested in the details you can refer to https://github.com/flutter/flutter/issues/138592 and https://github.com/google/material-design-icons/issues/1500 as well as the PR to the engine that fixed the problem https://github.com/flutter/flutter/pull/138937

You may want to file an issue within the material designs repo https://github.com/google/material-design-icons if you feel it is important.

I am going to close this issue - feel free to re-open it if you feel that is what needs to be done.

-tim

**Closed as completed by timmaffett** 2024-07-12 19:07 UTC
